name: artineering
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51083
title: Artineering - Santiago Montesdeoca
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5e4b34'
    - '#848a85'
    - '#d5c053'
    - '#100e0e'
  brandStrength: 0.7212474877014756
  lightness: 0.31097693205811083
  saturation: 0.631222328171134
  rhythmicContrast: 0.5
purpose: []
